# --- POSTGRESQL ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: my-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: order_manager
            - name: POSTGRES_USER
              value: franck
            - name: POSTGRES_PASSWORD
              value: root
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: my-app-dev
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

---
# --- VALKEY ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: my-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:8-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: valkey-service
  namespace: my-app-dev
spec:
  selector:
    app: valkey
  ports:
    - port: 6379
      targetPort: 6379

---
# --- MAILPIT ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  namespace: my-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
        - name: mailpit
          image: axllent/mailpit
          ports:
            - containerPort: 1025
            - containerPort: 8025
---
apiVersion: v1
kind: Service
metadata:
  name: mailpit-service
  namespace: my-app-dev
spec:
  selector:
    app: mailpit
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
    - name: http
      port: 8025
      targetPort: 8025